### ISSUE TITLE
Cannot assign a type as an expression. 

### ISSUE THREAD

**Issue by potentbanana** [variantdev/vals#12]
https://github.com/variantdev/vals/blob/9d1714c4386c65fe120e9427ec230599748aa27c/pkg/providers/echo/echo.go#L26

It's currently:
```
res := map[string]interface{}
```
Probably needs:
```
res := map[string]interface{}{}
```
or Assign it via ```var res map[string]interface{}```

**Comment by deadanon** [comment]
as it stands, this is the error without the fix above:

```
src/github.com/variantdev/vals/pkg/providers/echo/echo.go:26:9: type map[string]interface {} is not an expression
The command '/bin/sh -c go get github.com/roboll/helmfile' returned a non-zero code: 2```

**Comment by mumoshu** [comment]
I believe this was fixed in https://github.com/variantdev/vals/commit/34c03afad982a684ea418514e2812ddfd345a84a#diff-9bbff211e28239b582d0d53e1eb64ff3R26
Thanks for reporting!
