### ISSUE TITLE
Using AWS profiles for accessing SSM

### ISSUE THREAD

**Issue by Art3mK** [variantdev/vals#19]
Hey,

are there any way to instruct vals to use some AWS profile? IIUC from documentation golang SDK should support that, if `AWS_SDK_LOAD_CONFIG` is set to true and then profile could be selected with `AWS_PROFILE` or `AWS_DEFAULT_PROFILE`, but I can't get it working. My use case is to retrieve SSM parameter values in helmfile templates.

```
➜  ~/pr/q/eks-addons git:(aws-roles) ✗ aws sts get-caller-identity
{
    "UserId": "AIDADEADBEEF",
    "Account": "123",
    "Arn": "arn:aws:iam::123:user/artem.kajalainen"
}
➜  ~/pr/q/eks-addons git:(aws-roles) ✗ aws --profile example-dev-env sts get-caller-identity
{
    "UserId": "AROADEADBEEF:botocore-session-1584441505",
    "Account": "456",
    "Arn": "arn:aws:sts::456:assumed-role/circle-ci/botocore-session-1584441505"
}
➜  ~/pr/q/eks-addons git:(aws-roles) ✗ export AWS_DEFAULT_PROFILE=example-dev-env
➜  ~/pr/q/eks-addons git:(aws-roles) ✗ export AWS_PROFILE=example-dev-env
➜  ~/pr/q/eks-addons git:(aws-roles) ✗ export AWS_SDK_LOAD_CONFIG=true
➜  ~/pr/q/eks-addons git:(aws-roles) ✗ helmfile -e dev lint
Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories

Adding repo bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "traefik" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

Fetching stable/traefik
Fetching bitnami/external-dns
in ./helmfile.yaml: 2 errors:
err 0: failed to render values files "config/traefik1.7/dev-values.yaml": expand awsssm://dev/eu-north-1/eks/example-apps-cluster/public-ingress/lb-dns-name?region=eu-north-1: get parameter: AccessDeniedException: User: arn:aws:iam::123:user/artem.kajalainen is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-north-1:123:parameter/dev/eu-north-1/eks/example-apps-cluster/public-ingress/lb-dns-name
        status code: 400, request id: eb691d42-7f66-42fd-ae83-40528185b8be
err 1: failed to render values files "config/external-dns/dev-values.yaml": expand awsssm://dev/eu-north-1/eks/example-apps-cluster/external-dns/role-arn?region=eu-north-1: get parameter: AccessDeniedException: User: arn:aws:iam::123:user/artem.kajalainen is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-north-1:123:parameter/dev/eu-north-1/eks/example-apps-cluster/external-dns/role-arn
        status code: 400, request id: 9f680a2f-fd01-4882-a60f-abb830bdc8ab
```

are there any way to instruct vals to use some named aws profile or to assume role?

Thanks!

**Comment by mumoshu** [comment]
@Art3mK Hey! Thanks for your report.

I have not yet tested it myself but does https://github.com/variantdev/vals/commit/6c8d9cf188b8e0223f3ba7bb49a94c9c63c3289c fix the issue for you?

**Comment by Art3mK** [comment]
Hey @mumoshu, thanks for fast reply!

Yeah, it does work! However not in my use case, I'm exporting CI AWS creds in env variables, and tried to assume IAM role using those creds, but looks like SDK doesn't work this way. Looks like I'll be forced to assume role myself and then just expose temp STS credentials in env :)

However this works fine when profiles are configured "right" and credentials are stored in `~/.aws/credentials` file.

I think this could be closed then?

Thanks!

**Comment by Art3mK** [comment]
[Here](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/) (see `Credential and config loading order`) is exactly my case:

>The Environment variables for credentials will have precedence over shared config even if SharedConfig is enabled. To override this behavior, and use shared config credentials instead specify the session.Options.Profile, (e.g. when using credential_source=Environment to assume a role).

```
  sess, err := session.NewSessionWithOptions(session.Options{
	  Profile: "myProfile",
  })
```

Not sure how if this could be added to vals somehow

**Comment by Art3mK** [comment]
maybe you could read some env variable to set that `session.Options.Profile` to env `AWS_PROFILE` value, if that var is set?

like if `USE_AWS_PROFILE==1` -> set `session.Options.Profile` to `AWS_PROFILE`?

**Comment by mumoshu** [comment]
@Art3mK Thanks! Ah, so are you saying that `AWS_PROFILE` doesn't get loaded automatically by the aws go sdk?

Then, I think I'm fine to enhance `vals` to check for the existence of `AWS_PROFILE` and set it to session.Options.Profile` when existed.

Would that solve your problem?

**Comment by mumoshu** [comment]
> However this works fine when profiles are configured "right" and credentials are stored in ~/.aws/credentials file.

To be extra sure - which profile was loaded for you in this case? The profile pointed by `AWS_PROFILE` or the `default` one?

**Comment by mumoshu** [comment]
> However not in my use case, I'm exporting CI AWS creds in env variables, and tried to assume IAM role using those creds,

Oh, well interesting. I didn't know that that's possible with awscli(so it works with awscli, right?)

**Comment by mumoshu** [comment]
Well `AWS_PROFILE` and `AWS_DEFAULT_PROFILE` seems to be already considered.

```
type Options struct {
	// Provides config values for the SDK to use when creating service clients
	// and making API requests to services. Any value set in with this field
	// will override the associated value provided by the SDK defaults,
	// environment or config files where relevant.
	//
	// If not set, configuration values from from SDK defaults, environment,
	// config will be used.
	Config aws.Config

	// Overrides the config profile the Session should be created from. If not
	// set the value of the environment variable will be loaded (AWS_PROFILE,
	// or AWS_DEFAULT_PROFILE if the Shared Config is enabled).
	//
	// If not set and environment variables are not set the "default"
	// (DefaultSharedConfigProfile) will be used as the profile to load the
	// session config from.
	Profile string
```

Maybe what we need is to somehow "tweak" the selected profile to use credentials from `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`?

**Comment by Art3mK** [comment]
yeah, `AWS_PROFILE` works fine, if `AWS_SDK_LOAD_CONFIG==true` and there is no static credentials in environment. But if you will expose static credentials via `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, then those are used by SDK and `AWS_PROFILE` is ignored. AWS CLI works also exactly like that, but you can force aws cli to use specific profile for role assuming with `--profile`, and that profile could use credentials from environment (`credential_source = Environment`). So, to force SDK to use profile in this case, we need to pass `session.Options.Profile` to session.

So my proposal is to introduce new env variable for vals to check, for example `USE_AWS_PROFILE` or `FORCE_AWS_PROFILE `to control that `session.Options.Profile`.

So use cases:
```
AWS_SDK_LOAD_CONFIG=true
AWS_PROFILE=example
---
SDK will use named profile example to obtain credentials
``` 
```
AWS_SDK_LOAD_CONFIG=true
AWS_PROFILE=example
AWS_ACCESS_KEY_ID=abc
AWS_SECRET_ACCESS_KEY=abc
---
SDK will ignore AWS_PROFILE and shared config and use static credentials
``` 
```
AWS_SDK_LOAD_CONFIG=true
AWS_PROFILE=example
AWS_ACCESS_KEY_ID=abc
AWS_SECRET_ACCESS_KEY=abc
FORCE_AWS_PROFILE=true
---
vals will set session.Options.Profile to AWS_PROFILE, SDK will use example profile to obtain credentials.
``` 

How does it look you?

**Comment by mumoshu** [comment]
> yeah, `AWS_PROFILE` works fine, if `AWS_SDK_LOAD_CONFIG==true` and there is no static credentials in environment. But if you will expose static credentials via `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, then those are used by SDK and `AWS_PROFILE` is ignored. AWS CLI works also exactly like that, but you can force aws cli to use specific profile for role assuming with `--profile`, and that profile could use credentials from environment (`credential_source = Environment`). So, to force SDK to use profile in this case, we need to pass `session.Options.Profile` to session.

Thanks a lot for your explanation. That makes total sense. I have never realized that `--profile` paired with `credentials_source` could be used like that!

`FORCE_AWS_PROFILE=true` seems better to me.

**Comment by mumoshu** [comment]
@Art3mK I've implemented it in 9d65f55. Could you give it a try?

**Comment by Art3mK** [comment]
works like a charm ❤️ 🎉 

```
➜  ~/pr/fu/v/bin git:(master) echo "foo: ref+awsssm://dev/eu-north-1/eks/example-apps-cluster/external-dns/role-arn?region=eu-north-1" | ./vals eval -f -
expand awsssm://dev/eu-north-1/eks/example-apps-cluster/external-dns/role-arn?region=eu-north-1: get parameter: AccessDeniedException: User: arn:aws:iam::123456789012:user/artem.kajalainen is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-north-1:123456789012:parameter/dev/eu-north-1/eks/example-apps-cluster/external-dns/role-arn
	status code: 400, request id: b369e180-bc8e-470b-aa19-cbc4575c80f2
➜  ~/pr/fu/v/bin git:(master) export FORCE_AWS_PROFILE=true
➜  ~/pr/fu/v/bin git:(master) echo "foo: ref+awsssm://dev/eu-north-1/eks/example-apps-cluster/external-dns/role-arn?region=eu-north-1" | ./vals eval -f -
SSM: successfully retrieved key=/dev/eu-north-1/eks/example-apps-cluster/external-dns/role-arn
foo: arn:aws:iam::062474522373:role/example-apps-cluster-external-dns
```

Thanks a lot!

Will that be available in helmfile soon?

**Comment by mumoshu** [comment]
@Art3mK It's in Helmfile since v0.103.0 which has just been released 😃

**Comment by Art3mK** [comment]
Thanks a lot @mumoshu! I owe you a 🍺 🙂

**Comment by marcportabellaclotet-mt** [comment]
It is possible to add a cfg variable with the profile name:

if os.Getenv("FORCE_AWS_PROFILE") == "true" || profile != "" {
  if profile != "" {
    opts.Profile = profile
  } else {
    opts.Profile = os.Getenv("AWS_PROFILE")
  }
}

I have already tested with 
`echo "foo: ref+awsssm://dev/dov/token?profile=account" | bin/vals eval -f -
and it works.
Modified also the ssm.go and awssec.go..
...
p.Profile = cfg.String("profile")
...
sess := awsclicompat.NewSession(p.Region,p.Profile)

**Comment by mumoshu** [comment]
@marcportabellaclotet-mt Yes, I believe that's a valid feature request! Would you mind submitting a pull request for that?

**Comment by marcportabellaclotet-mt** [comment]
mmm, sure... but I do not have rights to create branches or PR on this repo....

**Comment by marcportabellaclotet-mt** [comment]
Thanks for merging @mumoshu ! It would be nice that this is ported to helmfile.
