### ISSUE TITLE
ref+vault fails with "no value found for key"

### ISSUE THREAD

**Issue by sirianni** [variantdev/vals#28]
I'm having problems getting vault ref to work properly.

```
$ vault kv get -field=secretContent "v1/prod/kv/foo"
<redacted>
```

```
$ echo "foo: ref+vault://v1/prod/kv/foo#/secretContent" | ./main eval -f -            
expand vault://v1/prod/kv/foo#/secretContent: no value found for key secretContent
```

**Comment by mumoshu** [comment]
@sirianni Hey! Neither `vault kv get` nor `ref` urls should contain `v1/` in the key.

```
$ echo $VAULT_ADDR
http://127.0.0.1:8200

$ vault secrets enable -version=1 -path prod/kv kv

$ vault write prod/kv/foo secretContent=CONTENT
Success! Data written to: prod/kv/foo

$ vault read -field secretContent prod/kv/foo
CONTENT

$ vault kv get -field secretContent prod/kv/foo
CONTENT

$ echo 'secret: ref+vault://prod/kv/foo#/secretContent' | vals eval -f -
secret: CONTENT
```

**Comment by sirianni** [comment]
Thanks @mumoshu !  The `v1` is our company's own naming scheme for vault.  

```
$ vault kv list "/v1/prod/kv/"              
Keys
----
<redacted>
```

**Comment by mumoshu** [comment]
@sirianni Thanks! I'm still unable to reproduce your issue.

```
$ vault secrets enable -version=1 -path v1/prod/kv kv
Success! Enabled the kv secrets engine at: v1/prod/kv/
$ vault write v1/prod/kv/foo secretContent=CONTENT
Success! Data written to: v1/prod/kv/foo
$ vault read -field secretContent v1/prod/kv/foo
CONTENT
$ vault kv get -field secretContent v1/prod/kv/foo
CONTENT
$ echo 'secret: ref+vault://v1/prod/kv/foo#/secretContent' | vals eval -f -
secret: CONTENT
$ vault kv list "/v1/prod/kv/"
Keys
----
foo
```


Would you mind sharing the exact steps to reproduce your issue? There may be slight difference in how we mount the kv backend?

**Comment by sirianni** [comment]
I've root caused the issue to our Vault installation using the "version 2" KV engine.  

You can see [here](https://github.com/hashicorp/vault/blob/master/command/kv_get.go#L102-L110) in the Vault CLI that for v2 KV stores, the string `data` is inserted into the path between the "mount point" and the "key path".  Unfortunately it does not seem that the Vault golang SDK does this automatically.

I was able to work around the issue by manually inserting `data` into the path.  In our Vault setup, the secrets store is (confusingly) mounted at `v1/prod/kv`
```
foo: ref+vault://v1/prod/kv/data/foo#/secretContent
```

https://github.com/BetterCloud/vault-java-driver/issues/114 has a good summary of the issue.

**Comment by mumoshu** [comment]
@sirianni Ah! That's good to know. Thank you so much for tracking it down to the root.

Maybe we'd better document a few examples with which `vault read` and `vault kv get` operations map to which ref URL at least?

I've also read the issue you've shared. Do you think we can somehow auto-detect the version of the kv backend requested and automatically inject the `data/` into the path depending on the version?

**Comment by sirianni** [comment]
> Do you think we can somehow auto-detect the version of the kv backend requested and automatically inject the data/ into the path depending on the version?

Yes, I think this is what the [vault CLI does](https://github.com/hashicorp/vault/blob/398f1a2bb3a4f52ca0bd936f9f65e76139ad5ba2/command/kv_helpers.go#L44)

**Comment by kevinjqiu** [comment]
We're hit with the same issue - migrating from v1 to v2 means we had to change _all_ vals references and manually add `data/` to the path.  I've created a PR https://github.com/variantdev/vals/pull/33 using vault CLI helper methods as @sirianni pointed out.
