### ISSUE TITLE
AWS SSM fetch deeper parameters to browse by path

### ISSUE THREAD

**Issue by johnmarcou** [variantdev/vals#31]
SSM provider can not fetch more than 1 level deep parameters.

### Context
Let's say AWS Parameter Store contains this structure:
```
/myteam/myapp/mykey01 = myval1
/myteam/myapp/mykey02 = myval2
/myteam/global/mykey03 = myval3
```

SSM parameter can be fetch like this:
```
key1: ref+awsssm://myteam/myapp/mykey01
```

If we are fetching multiple keys, we can use cache like this to fetch only once:
```
key1: ref+awsssm://myteam/myapp/#mykey01
key2: ref+awsssm://myteam/myapp/#mykey02
```

### The issue
If we want to cache one level upper, we get an error
```
key1: ref+awsssm://myteam/#myapp/mykey01
key2: ref+awsssm://myteam/#myapp/mykey02
key3: ref+awsssm://myteam/#global/mykey03

```
Here the error message:
```
err: expand awsssm://myteam/mydoc/#foo/bar: ssm: out.Parameters is empty
in ./helmfile.yaml: expand awsssm://myteam/#myapp/mykey01: ssm: out.Parameters is empty
```

### Troubleshoot
The provider is getting multiple parameters using `GetParametersByPathInput`:
https://github.com/variantdev/vals/blob/master/pkg/providers/ssm/ssm.go#L140

By default, this function returns only 1 level deep parameters.
I suggest to enable to `Recursive` option on that call.

### Workaround
Using `mode=singleparam` for now with YAML dict in a unique param.

**Comment by mumoshu** [comment]
@johnmarcou Thanks for reporting and the detailed diagnose! I believe this can be addressed by the `recursive=true` option added in v0.9.0.

Would you mind confirming that it works for you?

**Comment by johnmarcou** [comment]
Big thanks for that.
