### ISSUE TITLE
Vault auth_method kubernetes not supported?

### ISSUE THREAD

**Issue by hagsfdf** [variantdev/vals#46]
As I take a look in the code, it seems that only two `auth_method`s are supported : token and appRole.

In our case, vault is deployed as a pod in kubernetes cluster. And we want to integrate `vals` in our CD pipeline.
So I think supporting kubernetes as one of the auth_method is imperative. Otherwise we have to execute `vals` inside the pod.

I'm pretty new to the concept of vault. So it would be very appreciated if you can kindly give us an advice in our configuration.

**Comment by lodotek** [comment]
@iamjekyun What was your solution?
