### ISSUE TITLE
feat: environment variables provider

### ISSUE THREAD

**Issue by aslafy-z** [variantdev/vals#51]
Retrieving values from the environment would be a great addition.

It could look like this:

```shell
$ echo 'shell: "ref+env://SHELL"' | vals eval -f -
shell: /usr/bin/zsh
```

**Comment by s1111m** [comment]
Vote  https://github.com/variantdev/vals/pull/82

**Comment by mumoshu** [comment]
This has been added via #82 thanks to @max444ks1m. Closing as resolved! Thanks everyone for your support 🙏
