### ISSUE TITLE
Feature: Offical Github Action for setup vals

### ISSUE THREAD

**Issue by jkroepke** [variantdev/vals#59]
Hi, 

i would like to use vals on github actions.

Is an official action step planned that setups vals in a github action run? Like https://github.com/Azure/setup-helm or https://github.com/mdgreenwald/mozilla-sops-action

**Comment by mumoshu** [comment]
Hey! No, it isn't planned. But I'd appreciate it if anyone could create one and let me add a link to introduce it in vals' README. Thanks 😃

**Comment by jkroepke** [comment]
@mumoshu https://github.com/marketplace/actions/vals-binary-installer 

I'm using the action here, too: https://github.com/jkroepke/helm-secrets/pull/145
