### ISSUE TITLE
Missing `version` subcommand

### ISSUE THREAD

**Issue by lindhe** [variantdev/vals#62]
I wanted to double check that I was using the most recent version of `vals`. I expected there to be a `version` subcommand, similar to `kubectl version` and `helm version`, but turns out there's  no such command. Another common alternative is a `--version` flag, but that does not exist either.

I'm in favor of having both the subcommand and flag implemented, but if I had to choose I'd choose the subcommand since that's how `helm` does it, and `vals` is marketing itself as being "Helm-like".

## Expected behavior

```console
$ vals version
v0.14.0
```

## Actual behavior

```console
$ vals version
vals is a Helm-like configuration "Values" loader with support for various sources and merge strategies

Usage:
  vals [command]

Available Commands:
  eval		Evaluate a JSON/YAML document and replace any template expressions in it and prints the result
  exec		Populates the environment variables and executes the command
  env		Renders environment variables to be consumed by eval or a tool like direnv
  ksdecode	Decode YAML document(s) by converting Secret resources' "data" to "stringData" for use with "vals eval"

Use "vals [command] --help" for more infomation about a command
```

## System info

`vals` version: v0.14.0

**Comment by mumoshu** [comment]
Yeah, it would be great if it had `vals version` command!
