### ISSUE TITLE
Feature: Add support for reading Terraform remote state from http(s) backends 

### ISSUE THREAD

**Issue by emilhdiaz** [variantdev/vals#69]
Several providers, such as Terraform Cloud, Terraform Enterprise, and Gitlab support terraform remote state using the http backend. When these backends are used in conjunction with Terragrunt, the location of the local state file that points to the remote state is not deterministic (Terragrunt creates temporary working directories with random subfolders). Hence, it's impossible to point `ref+tfstate://...` to the correct location. Similar to how support was added for specific Cloud bucket backends, I'm proposing adding support for a generic http backend, something like `ref+https://...`

For reference, Gitlab (which is the backend I'm most interested in) exposed remote state at a URL like this: 
```
https://gitlab.com/api/v4/projects/${PROJECT_ID}/terraform/state/${RESOURCE_PATH}
```

**Comment by mumoshu** [comment]
Sounds good.
I have literally no experience with Terraform Cloud and Gitlab APIs, though.
How does authentication work in that case?

**Comment by emilhdiaz** [comment]
First of all, thanks for all the fantastic tools @mumoshu ! 

Both of these providers utilize HTTP headers for their authentication. 

Gitlab uses a combination of headers depending on the type of auth token being used: 
```
curl -H "PRIVATE-TOKEN: <PERSONAL_ACCESS_TOKEN>"
curl -H "DEPLOY-TOKEN: <DEPLOY_TOKEN>"
curl -H "JOB-TOKEN: <CI_JOB_TOKEN>"
```
More info here: https://docs.gitlab.com/ee/user/packages/terraform_module_registry/


While Terraform Cloud uses:
```
curl -H "Authorization: Bearer <TF_CLOUD_TOKEN>"
```
More info here: https://www.terraform.io/cloud-docs/api-docs/workspace-resources#sample-request

**Comment by mumoshu** [comment]
@emilhdiaz Thank you for your kinds words and the info!
That indeed makes sense.

I was also reading recent enhancements to tfstate-lookup which vals uses under the hood to read tfstate- https://github.com/fujiwara/tfstate-lookup/pull/30 seems to have added Terraform Cloud/Enterprise support.

There's the support for HTTP backend too so probably it's matter of just adding a few extra vals url scheme (like `tfstate+http://` and `tfstate+remote://` and pass correctly constructed URLs to tfstate-lookup.

**Comment by emilhdiaz** [comment]
Hi @mumoshu, a couple more updates from some research I did:

**Gitlab** also supports basic auth: 
```
curl -H "Authorization: Basic <base64Encode(<USERNAME>:<PERSONAL_ACCESS_TOKEN>)> https://gitlab.com/..."

OR 

curl https://<USERNAME>:<PERSONAL_ACCESS_TOKEN>@gitlab.com/...
```

The second form will work with a `tfstate+http://` scheme, but not the first. 


Unfortunately, **Terraform Cloud/Enterprise** does not support basic auth, only the following methods: 
1. Authorization header with Bearer token 
2. configure the remote backend `token` variable (NOT recommended, see https://www.terraform.io/language/settings/backends/remote#configuration-variables)  
2. `terraform login` CLI command which will (by default) store a token at `$HOME/.terraform.d/credentials.tfrc.json` (https://www.terraform.io/cli/auth) 
3. adding a `credentials {}` block to your `$HOME/.terraformrc` configuration file (https://www.terraform.io/cli/config/config-file#credentials-1)

I spent some time reading through the `tfstate-lookup` code and from what I can tell (and I'm not very familiar with Golang so forgive me if I misunderstood the codebase), I'm not seeing a way to pass credential information when using the http/remote URL schemes directly. It seems that the library still expects to read a local statefile, which in turn contains an http/remote backend configuration with credential information. 

This presents several problems:
a. We still have the problem, that with Terragrunt in the mix, the location of that local statefile is dynamic and unknown ahead of time.
b. For security reasons, many users don't (or rather _shouldn't_) include credential information directly in their backend configurations. They should use the `TF_*` environment variables to pass this information along to terraform. Therefore, these credentials are not guaranteed to be present in the local statefile.  
c. `tfstate-lookup` doesn't seem to support loading credentials from any environment variables or as CLI arguments. In fact, the author for that TF Cloud/Enterprise PR seems to call this out in the PR (https://github.com/fujiwara/tfstate-lookup/pull/30/files#r680533635), but it doesn't seem to have been implemented. 

With this new information would it make more sense to reduce the scope of this request to just the `tfstate+http://` implementation and consider the Terraform Cloud / Enterprise use case as a separate feature request?

**Comment by mumoshu** [comment]
@emilhdiaz Hey! Thanks for your patience. Can you confirm that https://github.com/variantdev/vals/pull/72 resolves this?

**Comment by mumoshu** [comment]
Closing this as resolved, but please feel free to reopen or submit another issue
