### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by sherifkayad** [variantdev/vals#75]
First of all I would like to express that this project is exactly what we need! Thanks for making that available.

Just was wondering why can't I find any Windows executable in the releases? Could you possible enable Windows support?

**Comment by mumoshu** [comment]
@sherifkayad Hey! It's just that I don't have a Windows machine to test, so if you could try building it on Windows, test it out, and possibly submit a pull request to add it to our supported platform, that would be much appreciated!

**Comment by sherifkayad** [comment]
I built it on Windows and it seems fine so far .. however I still need to do a couple of tests. Once I am done, will submit a PR. Thanks

**Comment by sherifkayad** [comment]
@mumoshu just to confirm, I need to only modify the goreleaser.yml file to support windows? Right? Sorry I am not that experienced with the go releaser.

**Comment by sherifkayad** [comment]
@mumoshu forget my last comment 😉 I was able to let the goreleaser generate a Windows release 😄 .. I tested locally against the generated Windows AMD64 binary and it was working like a charm.

Let me know if you have any feedback.

PR => https://github.com/variantdev/vals/pull/76
