### ISSUE TITLE
Feature Request | Allow Processing Multi-Resource Files

### ISSUE THREAD

**Issue by sherifkayad** [variantdev/vals#81]
Assuming you would have only one Yaml block in the file, `vals` would work great .. e.g. something like:
```myfile1.yml
apiVersion: v1
kind: Secret
metadata:
  name: some-secret
  namespace: default
stringData:
  mysql-password: refs+vault://secret/data/foo#/mykey
  mysql-root-password: vZQmqdGw3z
type: Opaque
```

However `vals` is unable to process something like:
```myfile2.yml
apiVersion: v1
kind: Secret
metadata:
  name: secret1
  namespace: default
stringData:
  mysql-password: refs+vault://secret/data/foo#/mykey
  mysql-root-password: vZQmqdGw3z
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
  namespace: default
stringData:
  key1: refs+vault://secret/data/bar#/mykey
  key2: whatever
type: Opaque
```

Basically Vals would only process the first Yaml block correctly (secret1) and would completely ignore the second secret

**Comment by mumoshu** [comment]
Thanks for bringing this up. Sounds like a valid feature request!

**Comment by sherifkayad** [comment]
@mumoshu would you work on that soon? .. Unfortunately I am not a Go expert to work on it myself .. let me know what you think
