### ISSUE TITLE
Bug: Triple dashes in YAML/JSON file to be evaluated

### ISSUE THREAD

**Issue by Weissger** [variantdev/vals#92]
Triple dashes in YAML/JSON file to be evaluated seem to allow only for a partial evaluation.

A file `foo.yaml` with following content:
```
foo: "bar"
---
baz: "qux"
```
only returns `foo: "bar"` when evaluated with `vals eval -f foo.yaml`

**Comment by mumoshu** [comment]
Ah, good catch! Almost certainly we might have missed interesting through all the YAML documents within the YAML file.  We'd need vals to iterate and output the new YAML docs separated by `---`s.
Are you able to contribute a pull request for that, by any chance? Thanks 🙏

**Comment by sherifkayad** [comment]
Relates to / duplicate #81
